version: '3.8'

services:
  particle-morph:
    image: nginx:alpine
    container_name: particle-morph-server
    ports:
      - "5100:80"
    volumes:
      - ./particle_morph.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped